// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC2NUWphoiMhB20Oe6G_RxjHhmYlDVVWQ',
    appId: '1:309615046516:android:33311e1324834a07248621',
    messagingSenderId: '309615046516',
    projectId: 'chatily-app-548bb',
    storageBucket: 'chatily-app-548bb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGTxCdehW-xsdjQncphrRmlcMhnSOkF-U',
    appId: '1:309615046516:ios:e19612f04f3f0a23248621',
    messagingSenderId: '309615046516',
    projectId: 'chatily-app-548bb',
    storageBucket: 'chatily-app-548bb.firebasestorage.app',
    iosBundleId: 'com.example.chatily',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGTxCdehW-xsdjQncphrRmlcMhnSOkF-U',
    appId: '1:309615046516:ios:e19612f04f3f0a23248621',
    messagingSenderId: '309615046516',
    projectId: 'chatily-app-548bb',
    storageBucket: 'chatily-app-548bb.firebasestorage.app',
    iosBundleId: 'com.example.chatily',
  );
}
